name: 🔧 GA-04 — Variáveis
on: workflow_dispatch
env:
  ambiente: development
jobs: 
  variavies: 
    runs-on: ubuntu-latest
    env: 
      ambiente: staging
    steps: 
      - name: Variável a nível de job
        run: echo "$ambiente"
      - name: Variável a nível de step 
        env: 
            ambiente: production
        run: echo "$ambiente"
 
