name: 🚀 GA-01 — First Workflow
on: workflow_dispatch
jobs: 
  print-messages:
    runs-on: ubuntu-latest
    steps: 
    - name: Step 1 
      run: echo "Primeiro step iniciado"
    - name: Step 2 
      run: echo "Segundo step iniciado"
    - name: Step 3 
      run: echo "Terceiro step iniciado"  
