name: 🔍 GA-02 — Investigar Runner
on: workflow_dispatch
jobs: 
  investigate-os:
    runs-on: ubuntu-latest
    steps: 
    - name: Usuário atual
      run: whoami
    - name: Diretorio atual
      run: pwd
    - name: Sistema operacional atual
      run: lsb_release -a 
    - name: Arquivos disponiveis
      run: ls -l
    - name: Espaço em disco atual
      run: df -h    
    - name: Criando arquivo no job atual e listando 
      run: | 
        touch cat.txt
        ls -l
  list-archive:
    runs-on: ubuntu-latest
    needs: investigate-os
    steps:
    - name: Listando arquivo em outro Job
      run: ls -l 