name: ⚡ GA-03 — Triggers
on: [workflow_dispatch, push, pull_request]
jobs:
  view-triggers: 
    runs-on: ubuntu-latest
    steps: 
      - name: 
        run: echo " ✅ Evento disparado por ${{github.event_name}}"