name: Second Action
on: workflow_dispatch
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código servidor github
        uses: actions/checkout@v3
      - name: Download do código
        uses: actions/download-artifact@v8
      - name: Upload código
        uses: actions/upload-artifact@v7
