name: Second Action
on: workflow_dispatch
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código servidor github
        uses: actions/checkout@v5
      
      - name: Upload código
        uses: actions/upload-artifact@v8
        with: 
          patch: .

      - name: Download do código
        uses: actions/download-artifact@v7
